"""modify users table

Revision ID: 9a489a864418
Revises: c3a95a396bf2
Create Date: 2023-03-06 17:32:39.377248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a489a864418'
down_revision = 'c3a95a396bf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users2_id'), 'users2', ['id'], unique=False)
    op.drop_column('users', 'name2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name2', mysql.VARCHAR(length=120), nullable=False))
    op.drop_index(op.f('ix_users2_id'), table_name='users2')
    op.drop_table('users2')
    # ### end Alembic commands ###
